baseURL = "/"
languageCode = "de"
title = "i am schulz"
theme = "iamschulz-hugo-theme"
contentDir = "iamschulz-hugo-content/content"
staticDir = "iamschulz-hugo-content/static"

[params]
  author = "Daniel Schulz"
  description = "and this is my website"

[taxonomies]
  category = "categories"

[minify]
  minifyOutput = true

[youtube]
  disable = false
  privacyEnhanced = true

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1