baseURL = "/"
languageCode = "de"
title = "i am schulz"
theme = "iamschulz-hugo-theme"
contentDir = "iamschulz-hugo-content/content"
staticDir = "iamschulz-hugo-content/static"

[params]
  author = "Daniel Schulz"
  description = "and this is my website"

[taxonomies]
  category = "categories"

[menu]
  [[menu.main]]
    name = "Tech"
    url = "/categories/tech/"
    pre = "code-solid"
    weight = -120

  [[menu.main]]
    name = "Video"
    url = "/categories/video/"
    pre = "video-solid"
    weight = -110

  [[menu.main]]
    name = "Art"
    url = "/categories/art/"
    pre = "palette-solid"
    weight = -100

[minify]
  minifyOutput = true

[youtube]
  disable = false
  privacyEnhanced = true

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1